import React from 'react';
import { Upload, X } from 'lucide-react';
import { toast } from 'sonner';
import AdminLayout from '@/components/AdminLayout';
import ImageUploader from '@/components/ImageUploader';
import { trpc } from '@/lib/trpc';
import { prepareImageForUpload } from '@/lib/image-upload';
import type { HomepageCtaContent, HomepageHeroContent, HomepageIntroContent, HomepageOurStoryContent, HomepageSectionContent, HomepageSectionKey, HomepageStoriesContent } from '@shared/homepage';

const ACCENT='#F5569B';
const input:React.CSSProperties={width:'100%',padding:'9px 12px',fontSize:13,background:'#f2f2f2',border:'1px solid #ddd',outline:'none',color:'#2d2d2d',boxSizing:'border-box'};
const label:React.CSSProperties={display:'block',fontSize:11,fontWeight:700,letterSpacing:'.1em',textTransform:'uppercase',color:'#888',marginBottom:7};
function Field({name,children}:{name:string;children:React.ReactNode}){return <div><label style={label}>{name}</label>{children}</div>}
function Text({value,onChange,area=false}:{value:string;onChange:(v:string)=>void;area?:boolean}){return area?<textarea rows={4} value={value} onChange={e=>onChange(e.target.value)} style={{...input,resize:'vertical'}}/>:<input value={value} onChange={e=>onChange(e.target.value)} style={input}/>}
function Color({name,value,onChange}:{name:string;value:string;onChange:(v:string)=>void}){return <Field name={name}><div style={{display:'flex',gap:10}}><input type="color" value={/^#[0-9a-f]{6}$/i.test(value)?value:'#000000'} onChange={e=>onChange(e.target.value)} style={{width:44,height:36}}/><Text value={value} onChange={onChange}/></div></Field>}
function Grid({children}:{children:React.ReactNode}){return <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:20}}>{children}</div>}

function MultiImageUploader({values,onChange,sourceLabel}:{values:string[];onChange:(values:string[])=>void;sourceLabel:string}){
 const fileRef=React.useRef<HTMLInputElement>(null);const [uploading,setUploading]=React.useState(false);const upload=trpc.media.upload.useMutation();
 const handleFiles=async(files:File[])=>{const images=files.filter(file=>file.type.startsWith('image/'));if(!images.length)return;setUploading(true);try{const uploaded:string[]=[];for(const file of images){const prepared=await prepareImageForUpload(file);const result=await upload.mutateAsync({filename:prepared.filename,base64:prepared.base64,mimeType:prepared.mimeType,fileSize:prepared.fileSize,source:'homepage-hero',sourceLabel,sourceUrl:'/',assetType:'general'});uploaded.push(result.url)}onChange([...values,...uploaded]);toast.success(`${uploaded.length} image${uploaded.length===1?'':'s'} uploaded`)}catch(error:any){toast.error(error.message||'Upload failed')}finally{setUploading(false);if(fileRef.current)fileRef.current.value=''}};
 return <div style={{marginTop:20}}><label style={label}>Banner Images</label>{values.length>0&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(150px,1fr))',gap:12,marginBottom:12}}>{values.map((url,index)=><div key={`${url}-${index}`} style={{position:'relative',height:105,background:'#e8e8e8',overflow:'hidden'}}><img src={url} alt={`Banner ${index+1}`} style={{width:'100%',height:'100%',objectFit:'cover'}}/><button type="button" onClick={()=>onChange(values.filter((_,itemIndex)=>itemIndex!==index))} title="Remove image" style={{position:'absolute',top:5,right:5,width:24,height:24,border:0,borderRadius:2,background:'rgba(0,0,0,.65)',color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer'}}><X size={13}/></button></div>)}</div>}<div onClick={()=>!uploading&&fileRef.current?.click()} onDrop={event=>{event.preventDefault();if(!uploading)handleFiles(Array.from(event.dataTransfer.files))}} onDragOver={event=>event.preventDefault()} style={{border:'1px dashed #ccc',padding:'18px 16px',cursor:uploading?'not-allowed':'pointer',display:'flex',alignItems:'center',justifyContent:'center',gap:8,color:'#888',fontSize:12,background:'#fafafa'}}><Upload size={15}/><span>{uploading?'Uploading images...':'Upload banner images (select or drop multiple files)'}</span></div><input ref={fileRef} type="file" accept="image/*" multiple style={{display:'none'}} onChange={event=>handleFiles(Array.from(event.target.files||[]))}/></div>
}

function VisibilitySwitch({checked,onChange}:{checked:boolean;onChange:(checked:boolean)=>void}){return <button type="button" role="switch" aria-checked={checked} onClick={()=>onChange(!checked)} style={{display:'flex',alignItems:'center',gap:9,border:0,background:'none',color:checked?ACCENT:'#999',fontSize:11,textTransform:'uppercase',cursor:'pointer'}}><span style={{position:'relative',display:'inline-block',width:38,height:21,borderRadius:999,background:checked?ACCENT:'#c8c8c8',transition:'background .2s'}}><span style={{position:'absolute',top:3,left:checked?20:3,width:15,height:15,borderRadius:'50%',background:'#fff',boxShadow:'0 1px 3px rgba(0,0,0,.25)',transition:'left .2s'}}/></span>{checked?'Visible':'Hidden'}</button>}

function SectionEditor({section}:{section:any}){
 const utils=trpc.useUtils();const [content,setContent]=React.useState<HomepageSectionContent>(section.content);const [visible,setVisible]=React.useState(section.isVisible);
 const update=trpc.homepage.updateSection.useMutation({onSuccess:()=>{utils.homepage.listSections.invalidate();utils.homepage.getPublicData.invalidate();toast.success(`${section.name} saved`)},onError:e=>toast.error(e.message)});
 const save=()=>update.mutate({id:section.id,isVisible:visible,content});const key=section.sectionKey as HomepageSectionKey;
 const image=(name:string,value:string,onChange:(v:string)=>void,source:string)=><ImageUploader label={name} value={value} onChange={onChange} category="homepage" source={source} sourceLabel={section.name} sourceUrl="/"/>;
 let fields:React.ReactNode=null;
 if(key==='hero'){const c=content as HomepageHeroContent;fields=<><Grid><Field name="Title"><Text value={c.title} onChange={v=>setContent({...c,title:v})}/></Field><Field name="Subtitle"><Text value={c.subtitle} onChange={v=>setContent({...c,subtitle:v})}/></Field><Field name="Overlay Opacity (%)"><input type="number" min="0" max="100" value={c.overlayOpacity} onChange={e=>setContent({...c,overlayOpacity:Number(e.target.value)})} style={input}/></Field></Grid><MultiImageUploader values={c.images.filter(Boolean)} onChange={images=>setContent({...c,images})} sourceLabel={section.name}/></>}
 if(key==='introduction'){const c=content as HomepageIntroContent;fields=<><Grid><Field name="Title"><Text value={c.title} onChange={v=>setContent({...c,title:v})}/></Field><Field name="Button Label"><Text value={c.buttonLabel} onChange={v=>setContent({...c,buttonLabel:v})}/></Field><Color name="Background Color" value={c.backgroundColor} onChange={v=>setContent({...c,backgroundColor:v})}/><Color name="Text Color" value={c.textColor} onChange={v=>setContent({...c,textColor:v})}/></Grid><div style={{marginTop:20}}><Field name="Content"><Text area value={c.content} onChange={v=>setContent({...c,content:v})}/></Field></div></>}
 if(key==='our-story'){const c=content as HomepageOurStoryContent;fields=<Grid><Field name="Show More Label"><Text value={c.showMoreLabel} onChange={v=>setContent({...c,showMoreLabel:v})}/></Field><Field name="Show Less Label"><Text value={c.showLessLabel} onChange={v=>setContent({...c,showLessLabel:v})}/></Field><Field name="Initially Visible Cards"><input type="number" min="1" value={c.initiallyVisible} onChange={e=>setContent({...c,initiallyVisible:Number(e.target.value)})} style={input}/></Field><Color name="Background Color" value={c.backgroundColor} onChange={v=>setContent({...c,backgroundColor:v})}/><div style={{gridColumn:'1/-1',fontSize:12,color:'#888'}}>Our Story card content is edited under “Our Story”. This panel controls how that section appears on the homepage.</div></Grid>}
 if(key==='explore'){fields=<div style={{fontSize:13,color:'#777',lineHeight:1.7}}>This section follows the fixed homepage design and content. Only its visibility can be changed.</div>}
 if(key==='stories'){const c=content as HomepageStoriesContent;const card=(i:number,v:any)=>setContent({...c,cards:c.cards.map((x,n)=>n===i?{...x,...v}:x)});fields=<><Color name="Section Background" value={c.backgroundColor} onChange={v=>setContent({...c,backgroundColor:v})}/>{c.cards.map((item,i)=><div key={i} style={{marginTop:24,paddingTop:20,borderTop:'1px solid #eee'}}><strong style={{fontSize:11,color:ACCENT,textTransform:'uppercase'}}>Story Category {i+1}</strong><Grid><Field name="Title"><Text value={item.title} onChange={v=>card(i,{title:v})}/></Field><Field name="Button Label"><Text value={item.buttonLabel} onChange={v=>card(i,{buttonLabel:v})}/></Field><Field name="Description"><Text area value={item.description} onChange={v=>card(i,{description:v})}/></Field><div>{image('Image',item.image,v=>card(i,{image:v}),`homepage-story-category-${i+1}`)}</div></Grid></div>)}</>}
 if(key==='features'){fields=<div style={{fontSize:13,color:'#777',lineHeight:1.7}}>This section follows the fixed homepage design and content. Only its visibility can be changed.</div>}
 if(key==='cta'){const c=content as HomepageCtaContent;fields=<><Grid><Field name="Title"><Text value={c.title} onChange={v=>setContent({...c,title:v})}/></Field><Field name="Button Label"><Text value={c.buttonLabel} onChange={v=>setContent({...c,buttonLabel:v})}/></Field><Color name="Background" value={c.backgroundColor} onChange={v=>setContent({...c,backgroundColor:v})}/><Color name="Text" value={c.textColor} onChange={v=>setContent({...c,textColor:v})}/></Grid><div style={{marginTop:18,padding:'12px 14px',background:'#fafafa',border:'1px solid #eee',fontSize:12,color:'#777'}}>Texture image and opacity are controlled from Media Library → Background Texture Image.</div></>}
 return <section style={{background:'#fff',border:'1px solid #e5e5e5',marginBottom:22}}><header style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'17px 22px',background:'#f7f7f7',borderBottom:'1px solid #eee'}}><div><strong style={{fontSize:14,letterSpacing:'.08em',textTransform:'uppercase'}}>{section.name}</strong><div style={{fontSize:11,color:'#aaa',marginTop:3}}>Homepage section</div></div><VisibilitySwitch checked={visible} onChange={setVisible}/></header><div style={{padding:26}}>{fields}<button type="button" onClick={save} disabled={update.isPending} style={{marginTop:26,padding:'10px 26px',background:ACCENT,color:'#fff',border:0,fontSize:12,textTransform:'uppercase',letterSpacing:'.1em'}}>{update.isPending?'Saving...':'Save Section'}</button></div></section>
}

export default function AdminHomepage(){const {data:sections=[],isLoading}=trpc.homepage.listSections.useQuery();return <AdminLayout title="Homepage"><div style={{padding:32,maxWidth:1050}}><h1 style={{fontSize:22,fontWeight:300,letterSpacing:'.1em',textTransform:'uppercase',margin:0}}>Homepage Sections</h1><p style={{fontSize:13,color:'#888',margin:'6px 0 28px'}}>These sections match the current homepage from top to bottom. Edit content and control visibility independently.</p>{isLoading?<div>Loading...</div>:sections.map(section=><SectionEditor key={section.id} section={section}/>)}</div></AdminLayout>}
