import React from 'react';
import { Edit2, Plus, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import AdminLayout from '@/components/AdminLayout';
import ImageUploader from '@/components/ImageUploader';
import { trpc } from '@/lib/trpc';
import { createDefaultExplorePage, normalizeExplorePage, type ExplorePageContent } from '@shared/explore';

const ACCENT='#F5569B';
const panel:React.CSSProperties={background:'#fff',border:'1px solid #eee',padding:28,marginBottom:24};
const input:React.CSSProperties={width:'100%',padding:'9px 12px',fontSize:13,background:'#f2f2f2',border:'1px solid #ddd',outline:'none',color:'#2d2d2d',boxSizing:'border-box'};
const label:React.CSSProperties={display:'block',fontSize:11,fontWeight:700,letterSpacing:'.1em',textTransform:'uppercase',color:'#888',marginBottom:7};
type Form={slug:string;title:string;isVisible:boolean;sortOrder:number;pageContent:ExplorePageContent};
function Field({name,children}:{name:string;children:React.ReactNode}){return <div><label style={label}>{name}</label>{children}</div>}
function Text({value,onChange,area=false}:{value:string;onChange:(v:string)=>void;area?:boolean}){return area?<textarea value={value} onChange={e=>onChange(e.target.value)} rows={3} style={{...input,resize:'vertical'}}/>:<input value={value} onChange={e=>onChange(e.target.value)} style={input}/>}
function Color({name,value,onChange}:{name:string;value:string;onChange:(v:string)=>void}){return <Field name={name}><div style={{display:'flex',gap:10}}><input type="color" value={/^#[0-9a-f]{6}$/i.test(value)?value:'#000000'} onChange={e=>onChange(e.target.value)} style={{width:44,height:36,border:'1px solid #ddd'}}/><Text value={value} onChange={onChange}/></div></Field>}
function Title({children}:{children:React.ReactNode}){return <div style={{fontSize:13,fontWeight:600,letterSpacing:'.12em',textTransform:'uppercase',paddingBottom:12,borderBottom:'1px solid #eee',marginBottom:22}}>{children}</div>}
function Grid({children}:{children:React.ReactNode}){return <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:20}}>{children}</div>}

function Editor({initial,pending,onSave,onCancel}:{initial:Form;pending:boolean;onSave:(f:Form)=>void;onCancel:()=>void}){
 const [form,setForm]=React.useState(initial); const page=form.pageContent;
 const root=<K extends keyof Form>(k:K,v:Form[K])=>setForm(f=>({...f,[k]:v}));
 const section=<K extends keyof ExplorePageContent>(k:K,v:Partial<ExplorePageContent[K]>)=>setForm(f=>({...f,pageContent:{...f.pageContent,[k]:{...f.pageContent[k],...v}}}));
 const img=(name:string,value:string,onChange:(v:string)=>void,source:string)=><ImageUploader label={name} value={value} onChange={onChange} category="explore" source={source} sourceLabel={form.title} sourceUrl={`/explore/${form.slug}`}/>;
 const updateDetail=(i:number,v:any)=>section('details',{items:page.details.items.map((x,n)=>n===i?{...x,...v}:x)});
 const updatePerspective=(i:number,v:any)=>section('perspectives',{items:page.perspectives.items.map((x,n)=>n===i?{...x,...v}:x)});
 const updateStory=(i:number,v:any)=>section('stories',{items:page.stories.items.map((x,n)=>n===i?{...x,...v}:x)});
 return <form onSubmit={e=>{e.preventDefault();onSave(form)}}>
  <div style={panel}><Title>Page Settings</Title><Grid><Field name="Admin Title"><Text value={form.title} onChange={v=>root('title',v)}/></Field><Field name="URL Slug"><Text value={form.slug} onChange={v=>root('slug',v.toLowerCase().replace(/[^a-z0-9-]/g,'-'))}/></Field><Field name="Sort Order"><input type="number" value={form.sortOrder} onChange={e=>root('sortOrder',Number(e.target.value))} style={input}/></Field><label style={{display:'flex',gap:8,alignItems:'center',fontSize:13}}><input type="checkbox" checked={form.isVisible} onChange={e=>root('isVisible',e.target.checked)}/> Show on public pages</label></Grid></div>
  <div style={panel}><Title>Hero</Title><Grid><Field name="Eyebrow"><Text value={page.hero.eyebrow} onChange={v=>section('hero',{eyebrow:v})}/></Field><Field name="Page Title"><Text value={page.hero.title} onChange={v=>section('hero',{title:v})}/></Field><Color name="Fallback Background" value={page.hero.backgroundColor} onChange={v=>section('hero',{backgroundColor:v})}/><Field name="Image Overlay (%)"><input type="number" min="0" max="100" value={page.hero.overlayOpacity} onChange={e=>section('hero',{overlayOpacity:Number(e.target.value)})} style={input}/></Field></Grid><div style={{marginTop:20}}><Field name="Subtitle"><Text area value={page.hero.subtitle} onChange={v=>section('hero',{subtitle:v})}/></Field></div><div style={{marginTop:20}}>{img('Hero Image',page.hero.image,v=>section('hero',{image:v}),'explore-hero')}</div></div>
  <div style={panel}><Title>Introduction</Title><Grid><Field name="Eyebrow"><Text value={page.introduction.eyebrow} onChange={v=>section('introduction',{eyebrow:v})}/></Field><Color name="Background Color" value={page.introduction.backgroundColor} onChange={v=>section('introduction',{backgroundColor:v})}/><Color name="Text Color" value={page.introduction.textColor} onChange={v=>section('introduction',{textColor:v})}/></Grid><div style={{marginTop:20}}><Field name="Introduction Text"><Text area value={page.introduction.text} onChange={v=>section('introduction',{text:v})}/></Field></div></div>
  <div style={panel}><Title>Visual Story</Title><Grid><Field name="Eyebrow"><Text value={page.visual.eyebrow} onChange={v=>section('visual',{eyebrow:v})}/></Field><Field name="Title"><Text value={page.visual.title} onChange={v=>section('visual',{title:v})}/></Field><Color name="Background Color" value={page.visual.backgroundColor} onChange={v=>section('visual',{backgroundColor:v})}/></Grid>{page.visual.paragraphs.map((p,i)=><div style={{marginTop:20}} key={i}><Field name={`Paragraph ${i+1}`}><Text area value={p} onChange={v=>section('visual',{paragraphs:page.visual.paragraphs.map((x,n)=>n===i?v:x)})}/></Field></div>)}<Grid>{page.visual.images.map((v,i)=><div style={{marginTop:20}} key={i}>{img(`Visual Image ${i+1}`,v,value=>section('visual',{images:page.visual.images.map((x,n)=>n===i?value:x)}),`explore-visual-${i+1}`)}</div>)}</Grid></div>
  <div style={panel}><Title>Details Gallery</Title><Grid><Field name="Eyebrow"><Text value={page.details.eyebrow} onChange={v=>section('details',{eyebrow:v})}/></Field><Field name="Title"><Text value={page.details.title} onChange={v=>section('details',{title:v})}/></Field><Color name="Background Color" value={page.details.backgroundColor} onChange={v=>section('details',{backgroundColor:v})}/><Field name="Description"><Text area value={page.details.description} onChange={v=>section('details',{description:v})}/></Field></Grid>{page.details.items.map((item,i)=><div key={i} style={{borderTop:'1px solid #eee',paddingTop:20,marginTop:22}}><Field name={`Item ${i+1} Title`}><Text value={item.title} onChange={v=>updateDetail(i,{title:v})}/></Field><div style={{marginTop:14}}>{img(`Item ${i+1} Image`,item.image,v=>updateDetail(i,{image:v}),`explore-detail-${i+1}`)}</div></div>)}</div>
  <div style={panel}><Title>Statement</Title><Grid><Field name="Eyebrow"><Text value={page.statement.eyebrow} onChange={v=>section('statement',{eyebrow:v})}/></Field><Color name="Background Color" value={page.statement.backgroundColor} onChange={v=>section('statement',{backgroundColor:v})}/><Color name="Text Color" value={page.statement.textColor} onChange={v=>section('statement',{textColor:v})}/></Grid><div style={{marginTop:20}}><Field name="Statement"><Text area value={page.statement.text} onChange={v=>section('statement',{text:v})}/></Field></div></div>
  <div style={panel}><Title>Related Perspectives</Title><Grid><Field name="Eyebrow"><Text value={page.perspectives.eyebrow} onChange={v=>section('perspectives',{eyebrow:v})}/></Field><Color name="Background Color" value={page.perspectives.backgroundColor} onChange={v=>section('perspectives',{backgroundColor:v})}/></Grid>{page.perspectives.items.map((item,i)=><div key={i} style={{borderTop:'1px solid #eee',paddingTop:20,marginTop:22}}><Grid><Field name="Title"><Text value={item.title} onChange={v=>updatePerspective(i,{title:v})}/></Field><Field name="Link"><Text value={item.href} onChange={v=>updatePerspective(i,{href:v})}/></Field><Field name="Description"><Text area value={item.description} onChange={v=>updatePerspective(i,{description:v})}/></Field><div>{img('Image',item.image,v=>updatePerspective(i,{image:v}),`explore-perspective-${i+1}`)}</div></Grid></div>)}</div>
  <div style={panel}><Title>Related Stories</Title><Grid><Field name="Eyebrow"><Text value={page.stories.eyebrow} onChange={v=>section('stories',{eyebrow:v})}/></Field><Field name="Title"><Text value={page.stories.title} onChange={v=>section('stories',{title:v})}/></Field><Field name="View All Label"><Text value={page.stories.viewAllLabel} onChange={v=>section('stories',{viewAllLabel:v})}/></Field><Field name="View All Link"><Text value={page.stories.viewAllHref} onChange={v=>section('stories',{viewAllHref:v})}/></Field><Color name="Background Color" value={page.stories.backgroundColor} onChange={v=>section('stories',{backgroundColor:v})}/></Grid>{page.stories.items.map((item,i)=><div key={i} style={{borderTop:'1px solid #eee',paddingTop:20,marginTop:22}}><Grid><Field name="Category"><Text value={item.category} onChange={v=>updateStory(i,{category:v})}/></Field><Field name="Title"><Text value={item.title} onChange={v=>updateStory(i,{title:v})}/></Field><Field name="Link"><Text value={item.href} onChange={v=>updateStory(i,{href:v})}/></Field><div>{img('Image',item.image,v=>updateStory(i,{image:v}),`explore-story-${i+1}`)}</div></Grid></div>)}</div>
  <div style={panel}><Title>CTA</Title><Grid><Field name="Eyebrow"><Text value={page.cta.eyebrow} onChange={v=>section('cta',{eyebrow:v})}/></Field><Field name="Title"><Text value={page.cta.title} onChange={v=>section('cta',{title:v})}/></Field><Field name="Button Label"><Text value={page.cta.buttonLabel} onChange={v=>section('cta',{buttonLabel:v})}/></Field><Field name="Button Link"><Text value={page.cta.buttonHref} onChange={v=>section('cta',{buttonHref:v})}/></Field><Color name="Background" value={page.cta.backgroundColor} onChange={v=>section('cta',{backgroundColor:v})}/><Color name="Text" value={page.cta.textColor} onChange={v=>section('cta',{textColor:v})}/><Color name="Button Background" value={page.cta.buttonBackgroundColor} onChange={v=>section('cta',{buttonBackgroundColor:v})}/><Color name="Button Text" value={page.cta.buttonTextColor} onChange={v=>section('cta',{buttonTextColor:v})}/></Grid><Grid><div style={{marginTop:20}}>{img('Texture Image',page.cta.textureImage,v=>section('cta',{textureImage:v}),'explore-cta')}</div><div style={{marginTop:20}}><Field name="Texture Opacity (%)"><input type="number" min="0" max="100" value={page.cta.textureOpacity} onChange={e=>section('cta',{textureOpacity:Number(e.target.value)})} style={input}/></Field></div></Grid></div>
  <div style={{display:'flex',gap:12,marginBottom:32}}><button disabled={pending} style={{padding:'11px 30px',background:ACCENT,color:'#fff',border:0,cursor:'pointer'}}>{pending?'Saving...':'Save Complete Page'}</button><button type="button" onClick={onCancel} style={{padding:'10px 24px',background:'transparent',border:'1px solid #ddd'}}>Cancel</button></div>
 </form>
}

export default function AdminExplore(){
 const utils=trpc.useUtils(); const {data:sections=[],isLoading}=trpc.explore.listSections.useQuery(); const [editing,setEditing]=React.useState<number|'new'|null>(null);
 const invalidate=()=>Promise.all([utils.explore.listSections.invalidate(),utils.explore.listPublicSections.invalidate()]);
 const create=trpc.explore.createSection.useMutation({onSuccess:()=>{invalidate();setEditing(null);toast.success('Explore page created')},onError:e=>toast.error(e.message)});
 const update=trpc.explore.updateSection.useMutation({onSuccess:()=>{invalidate();setEditing(null);toast.success('Explore page saved')},onError:e=>toast.error(e.message)});
 const remove=trpc.explore.deleteSection.useMutation({onSuccess:()=>{invalidate();toast.success('Explore page deleted')},onError:e=>toast.error(e.message)});
 const current=editing==='new'?null:sections.find(x=>x.id===editing); const form:Form=current?{slug:current.slug,title:current.title,isVisible:current.isVisible,sortOrder:current.sortOrder,pageContent:normalizeExplorePage(current.pageContent,current.slug)}:{slug:'',title:'New Explore Page',isVisible:true,sortOrder:sections.length,pageContent:createDefaultExplorePage('village-life')};
 return <AdminLayout title="Explore"><div style={{padding:32,maxWidth:1050}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:28}}><div><h1 style={{fontSize:22,fontWeight:300,letterSpacing:'.1em',textTransform:'uppercase',margin:0}}>Explore Pages</h1><p style={{fontSize:13,color:'#888'}}>Edit every section, image, text, link and color used by the Explore template.</p></div>{editing===null&&<button onClick={()=>setEditing('new')} style={{display:'flex',gap:8,padding:'10px 20px',background:ACCENT,color:'#fff',border:0}}><Plus size={14}/> Add Page</button>}</div>{editing!==null?<Editor key={editing} initial={form} pending={create.isPending||update.isPending} onCancel={()=>setEditing(null)} onSave={value=>current?update.mutate({id:current.id,...value}):create.mutate(value)}/>:isLoading?<div>Loading...</div>:<div style={{background:'#fff',border:'1px solid #eee'}}>{sections.map((item,i)=><div key={item.id} style={{display:'grid',gridTemplateColumns:'1fr 100px 100px',padding:18,background:i%2?'#fff':'#f7f7f7',borderBottom:'1px solid #eee'}}><div><div>{item.title}</div><small style={{color:'#999'}}>/explore/{item.slug} · Order {item.sortOrder}</small></div><div style={{fontSize:11,color:item.isVisible?ACCENT:'#aaa'}}>{item.isVisible?'VISIBLE':'HIDDEN'}</div><div><button onClick={()=>setEditing(item.id)} style={{border:0,background:'none'}}><Edit2 size={15}/></button><button onClick={()=>confirm(`Delete “${item.title}”?`)&&remove.mutate({id:item.id})} style={{border:0,background:'none',color:'#b00020'}}><Trash2 size={15}/></button></div></div>)}</div>}</div></AdminLayout>
}
