import React from 'react';
import { Eye, EyeOff, Plus, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import AdminLayout from '@/components/AdminLayout';
import ImageUploader from '@/components/ImageUploader';
import { trpc } from '@/lib/trpc';
import type { HomepageCtaContent, HomepageFeaturesContent, HomepageHeroContent, HomepageIntroContent, HomepageOurStoryContent, HomepageSectionContent, HomepageSectionKey, HomepageStoriesContent } from '@shared/homepage';

const ACCENT='#F5569B';
const input:React.CSSProperties={width:'100%',padding:'9px 12px',fontSize:13,background:'#f2f2f2',border:'1px solid #ddd',outline:'none',color:'#2d2d2d',boxSizing:'border-box'};
const label:React.CSSProperties={display:'block',fontSize:11,fontWeight:700,letterSpacing:'.1em',textTransform:'uppercase',color:'#888',marginBottom:7};
function Field({name,children}:{name:string;children:React.ReactNode}){return <div><label style={label}>{name}</label>{children}</div>}
function Text({value,onChange,area=false}:{value:string;onChange:(v:string)=>void;area?:boolean}){return area?<textarea rows={4} value={value} onChange={e=>onChange(e.target.value)} style={{...input,resize:'vertical'}}/>:<input value={value} onChange={e=>onChange(e.target.value)} style={input}/>}
function Color({name,value,onChange}:{name:string;value:string;onChange:(v:string)=>void}){return <Field name={name}><div style={{display:'flex',gap:10}}><input type="color" value={/^#[0-9a-f]{6}$/i.test(value)?value:'#000000'} onChange={e=>onChange(e.target.value)} style={{width:44,height:36}}/><Text value={value} onChange={onChange}/></div></Field>}
function Grid({children}:{children:React.ReactNode}){return <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:20}}>{children}</div>}

function SectionEditor({section}:{section:any}){
 const utils=trpc.useUtils();const [content,setContent]=React.useState<HomepageSectionContent>(section.content);const [visible,setVisible]=React.useState(section.isVisible);
 const update=trpc.homepage.updateSection.useMutation({onSuccess:()=>{utils.homepage.listSections.invalidate();utils.homepage.getPublicData.invalidate();toast.success(`${section.name} saved`)},onError:e=>toast.error(e.message)});
 const save=()=>update.mutate({id:section.id,isVisible:visible,content});const key=section.sectionKey as HomepageSectionKey;
 const image=(name:string,value:string,onChange:(v:string)=>void,source:string)=><ImageUploader label={name} value={value} onChange={onChange} category="homepage" source={source} sourceLabel={section.name} sourceUrl="/"/>;
 let fields:React.ReactNode=null;
 if(key==='hero'){const c=content as HomepageHeroContent;fields=<><Grid><Field name="Title"><Text value={c.title} onChange={v=>setContent({...c,title:v})}/></Field><Field name="Subtitle"><Text value={c.subtitle} onChange={v=>setContent({...c,subtitle:v})}/></Field><Field name="Overlay Opacity (%)"><input type="number" min="0" max="100" value={c.overlayOpacity} onChange={e=>setContent({...c,overlayOpacity:Number(e.target.value)})} style={input}/></Field></Grid>{c.images.map((url,i)=><div key={i} style={{marginTop:20,paddingTop:18,borderTop:'1px solid #eee'}}>{image(`Hero Image ${i+1}`,url,v=>setContent({...c,images:c.images.map((x,n)=>n===i?v:x)}),`homepage-hero-${i+1}`)}{c.images.length>1&&<button type="button" onClick={()=>setContent({...c,images:c.images.filter((_,n)=>n!==i)})} style={{marginTop:8,border:0,background:'none',color:'#b00020',display:'flex',gap:6}}><Trash2 size={14}/> Remove</button>}</div>)}<button type="button" onClick={()=>setContent({...c,images:[...c.images,'']})} style={{marginTop:16,border:'1px solid #ddd',background:'#fff',padding:'8px 14px',display:'flex',gap:7}}><Plus size={14}/> Add Hero Image</button></>}
 if(key==='introduction'){const c=content as HomepageIntroContent;fields=<><Grid><Field name="Title"><Text value={c.title} onChange={v=>setContent({...c,title:v})}/></Field><Field name="Button Label"><Text value={c.buttonLabel} onChange={v=>setContent({...c,buttonLabel:v})}/></Field><Color name="Background Color" value={c.backgroundColor} onChange={v=>setContent({...c,backgroundColor:v})}/><Color name="Text Color" value={c.textColor} onChange={v=>setContent({...c,textColor:v})}/></Grid><div style={{marginTop:20}}><Field name="Content"><Text area value={c.content} onChange={v=>setContent({...c,content:v})}/></Field></div></>}
 if(key==='our-story'){const c=content as HomepageOurStoryContent;fields=<Grid><Field name="Show More Label"><Text value={c.showMoreLabel} onChange={v=>setContent({...c,showMoreLabel:v})}/></Field><Field name="Show Less Label"><Text value={c.showLessLabel} onChange={v=>setContent({...c,showLessLabel:v})}/></Field><Field name="Initially Visible Cards"><input type="number" min="1" value={c.initiallyVisible} onChange={e=>setContent({...c,initiallyVisible:Number(e.target.value)})} style={input}/></Field><Color name="Background Color" value={c.backgroundColor} onChange={v=>setContent({...c,backgroundColor:v})}/><div style={{gridColumn:'1/-1',fontSize:12,color:'#888'}}>Our Story card content is edited under “Our Story”. This panel controls how that section appears on the homepage.</div></Grid>}
 if(key==='explore'){fields=<div style={{fontSize:13,color:'#777',lineHeight:1.7}}>This section follows the fixed homepage design and content. Only its visibility can be changed.</div>}
 if(key==='stories'){const c=content as HomepageStoriesContent;const card=(i:number,v:any)=>setContent({...c,cards:c.cards.map((x,n)=>n===i?{...x,...v}:x)});fields=<><Color name="Section Background" value={c.backgroundColor} onChange={v=>setContent({...c,backgroundColor:v})}/>{c.cards.map((item,i)=><div key={i} style={{marginTop:24,paddingTop:20,borderTop:'1px solid #eee'}}><strong style={{fontSize:11,color:ACCENT,textTransform:'uppercase'}}>Story Category {i+1}</strong><Grid><Field name="Title"><Text value={item.title} onChange={v=>card(i,{title:v})}/></Field><Field name="Button Label"><Text value={item.buttonLabel} onChange={v=>card(i,{buttonLabel:v})}/></Field><Field name="Description"><Text area value={item.description} onChange={v=>card(i,{description:v})}/></Field><div>{image('Image',item.image,v=>card(i,{image:v}),`homepage-story-category-${i+1}`)}</div></Grid></div>)}</>}
 if(key==='features'){const c=content as HomepageFeaturesContent;fields=<><Grid><Field name="Section Title"><Text value={c.title} onChange={v=>setContent({...c,title:v})}/></Field><Color name="Background Color" value={c.backgroundColor} onChange={v=>setContent({...c,backgroundColor:v})}/></Grid><Grid>{c.items.map((item,i)=><Field key={i} name={`Feature ${i+1}`}><Text value={item.title} onChange={v=>setContent({...c,items:c.items.map((x,n)=>n===i?{title:v}:x)})}/></Field>)}</Grid></>}
 if(key==='cta'){const c=content as HomepageCtaContent;fields=<><Grid><Field name="Title"><Text value={c.title} onChange={v=>setContent({...c,title:v})}/></Field><Field name="Button Label"><Text value={c.buttonLabel} onChange={v=>setContent({...c,buttonLabel:v})}/></Field><Color name="Background" value={c.backgroundColor} onChange={v=>setContent({...c,backgroundColor:v})}/><Color name="Text" value={c.textColor} onChange={v=>setContent({...c,textColor:v})}/><Color name="Button Background" value={c.buttonBackgroundColor} onChange={v=>setContent({...c,buttonBackgroundColor:v})}/><Color name="Button Text" value={c.buttonTextColor} onChange={v=>setContent({...c,buttonTextColor:v})}/><Field name="Texture Opacity (%)"><input type="number" min="0" max="100" value={c.textureOpacity} onChange={e=>setContent({...c,textureOpacity:Number(e.target.value)})} style={input}/></Field></Grid><div style={{marginTop:20}}>{image('Texture Image',c.textureImage,v=>setContent({...c,textureImage:v}),'homepage-cta')}</div></>}
 return <section style={{background:'#fff',border:'1px solid #e5e5e5',marginBottom:22}}><header style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'17px 22px',background:'#f7f7f7',borderBottom:'1px solid #eee'}}><div><strong style={{fontSize:14,letterSpacing:'.08em',textTransform:'uppercase'}}>{section.name}</strong><div style={{fontSize:11,color:'#aaa',marginTop:3}}>Homepage section</div></div><button type="button" onClick={()=>setVisible(!visible)} style={{display:'flex',alignItems:'center',gap:8,border:0,background:'none',color:visible?ACCENT:'#999',fontSize:11,textTransform:'uppercase'}}>{visible?<Eye size={15}/>:<EyeOff size={15}/>} {visible?'Visible':'Hidden'}</button></header><div style={{padding:26}}>{fields}<button type="button" onClick={save} disabled={update.isPending} style={{marginTop:26,padding:'10px 26px',background:ACCENT,color:'#fff',border:0,fontSize:12,textTransform:'uppercase',letterSpacing:'.1em'}}>{update.isPending?'Saving...':'Save Section'}</button></div></section>
}

export default function AdminHomepage(){const {data:sections=[],isLoading}=trpc.homepage.listSections.useQuery();return <AdminLayout title="Homepage"><div style={{padding:32,maxWidth:1050}}><h1 style={{fontSize:22,fontWeight:300,letterSpacing:'.1em',textTransform:'uppercase',margin:0}}>Homepage Sections</h1><p style={{fontSize:13,color:'#888',margin:'6px 0 28px'}}>These sections match the current homepage from top to bottom. Edit content and control visibility independently.</p>{isLoading?<div>Loading...</div>:sections.map(section=><SectionEditor key={section.id} section={section}/>)}</div></AdminLayout>}
