import React from 'react';
import { Edit2, Plus, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import AdminLayout from '@/components/AdminLayout';
import ImageUploader from '@/components/ImageUploader';
import { trpc } from '@/lib/trpc';
import { createDefaultOurStoryPage, normalizeOurStoryPage, type OurStoryPageContent } from '@shared/our-story';

const ACCENT = '#F5569B';
const panel: React.CSSProperties = { background: '#fff', border: '1px solid #eee', padding: 28, marginBottom: 24 };
const labelStyle: React.CSSProperties = { display: 'block', fontSize: 11, fontWeight: 700, letterSpacing: '.1em', textTransform: 'uppercase', color: '#888', marginBottom: 7 };
const inputStyle: React.CSSProperties = { width: '100%', padding: '9px 12px', fontSize: 13, background: '#f2f2f2', border: '1px solid #ddd', outline: 'none', color: '#2d2d2d', boxSizing: 'border-box' };

type StoryForm = { slug: string; eyebrow: string; title: string; content: string; image: string; isVisible: boolean; sortOrder: number; pageContent: OurStoryPageContent };

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><label style={labelStyle}>{label}</label>{children}</div>; }
function Input({ value, onChange, required }: { value: string; onChange: (value: string) => void; required?: boolean }) { return <input required={required} value={value} onChange={event => onChange(event.target.value)} style={inputStyle} />; }
function TextArea({ value, onChange, rows = 4 }: { value: string; onChange: (value: string) => void; rows?: number }) { return <textarea required value={value} onChange={event => onChange(event.target.value)} rows={rows} style={{ ...inputStyle, resize: 'vertical' }} />; }
function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { const safe = /^#[0-9a-f]{6}$/i.test(value) ? value : '#000000'; return <Field label={label}><div style={{ display: 'flex', gap: 10, alignItems: 'center' }}><input type="color" value={safe} onChange={event => onChange(event.target.value)} style={{ width: 44, height: 36, padding: 0, border: '1px solid #ddd', cursor: 'pointer' }} /><Input value={value} onChange={onChange} /></div></Field>; }
function PanelTitle({ children }: { children: React.ReactNode }) { return <div style={{ fontSize: 13, fontWeight: 600, letterSpacing: '.12em', textTransform: 'uppercase', color: '#1a1a1a', paddingBottom: 12, borderBottom: '1px solid #eee', marginBottom: 22 }}>{children}</div>; }

function StoryEditor({ initial, isPending, onSave, onCancel }: { initial: StoryForm; isPending: boolean; onSave: (form: StoryForm) => void; onCancel: () => void }) {
  const [form, setForm] = React.useState(initial);
  const update = <K extends keyof StoryForm>(key: K, value: StoryForm[K]) => setForm(current => ({ ...current, [key]: value }));
  const updatePage = <K extends keyof OurStoryPageContent>(key: K, value: Partial<OurStoryPageContent[K]>) => setForm(current => ({ ...current, pageContent: { ...current.pageContent, [key]: { ...current.pageContent[key], ...value } } }));
  const page = form.pageContent;
  const updatePillar = (index: number, value: Partial<OurStoryPageContent['pillars']['items'][number]>) => updatePage('pillars', { items: page.pillars.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...value } : item) });

  return <form onSubmit={event => { event.preventDefault(); onSave(form); }}>
    <div style={panel}><PanelTitle>Page & Homepage Card</PanelTitle><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}><Field label="Card Title *"><Input required value={form.title} onChange={value => update('title', value)} /></Field><Field label="Card Eyebrow"><Input value={form.eyebrow} onChange={value => update('eyebrow', value)} /></Field><Field label="URL Slug *"><Input required value={form.slug} onChange={value => update('slug', value.toLowerCase().replace(/[^a-z0-9-]/g, '-'))} /></Field><Field label="Sort Order"><input type="number" value={form.sortOrder} onChange={event => update('sortOrder', Number(event.target.value))} style={inputStyle} /></Field></div><div style={{ marginTop: 20 }}><Field label="Card Description *"><TextArea value={form.content} onChange={value => update('content', value)} /></Field></div><div style={{ marginTop: 20 }}><ImageUploader label="Card Image" value={form.image} onChange={value => update('image', value)} category="about" source="our-story-card" sourceLabel={form.title || 'Our Story'} sourceUrl={`/our-story/${form.slug}`} /></div><label style={{ display: 'flex', gap: 8, alignItems: 'center', marginTop: 20, fontSize: 13, color: '#555' }}><input type="checkbox" checked={form.isVisible} onChange={event => update('isVisible', event.target.checked)} /> Show on public pages</label></div>

    <div style={panel}><PanelTitle>Hero</PanelTitle><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}><Field label="Eyebrow"><Input value={page.hero.eyebrow} onChange={value => updatePage('hero', { eyebrow: value })} /></Field><Field label="Page Title"><Input value={page.hero.title} onChange={value => updatePage('hero', { title: value })} /></Field></div><div style={{ marginTop: 20 }}><Field label="Subtitle"><TextArea value={page.hero.subtitle} onChange={value => updatePage('hero', { subtitle: value })} rows={3} /></Field></div><div style={{ marginTop: 20 }}><ImageUploader label="Hero Image" value={page.hero.image} onChange={value => updatePage('hero', { image: value })} category="about" source="our-story-hero" sourceLabel={form.title} sourceUrl={`/our-story/${form.slug}`} /></div></div>

    <div style={panel}><PanelTitle>01 — Introduction</PanelTitle><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}><Field label="Eyebrow"><Input value={page.introduction.eyebrow} onChange={value => updatePage('introduction', { eyebrow: value })} /></Field><ColorField label="Background Color" value={page.introduction.backgroundColor} onChange={value => updatePage('introduction', { backgroundColor: value })} /></div><div style={{ marginTop: 20 }}><Field label="Title"><Input value={page.introduction.title} onChange={value => updatePage('introduction', { title: value })} /></Field></div>{page.introduction.paragraphs.map((paragraph, index) => <div key={index} style={{ marginTop: 20 }}><Field label={`Paragraph ${index + 1}`}><TextArea value={paragraph} onChange={value => updatePage('introduction', { paragraphs: page.introduction.paragraphs.map((item, itemIndex) => itemIndex === index ? value : item) })} rows={3} /></Field></div>)}<div style={{ marginTop: 20 }}><ImageUploader label="Introduction Image" value={page.introduction.image} onChange={value => updatePage('introduction', { image: value })} category="about" source="our-story-introduction" sourceLabel={form.title} sourceUrl={`/our-story/${form.slug}`} /></div></div>

    <div style={panel}><PanelTitle>02 — Quote Section</PanelTitle><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}><Field label="Eyebrow"><Input value={page.quote.eyebrow} onChange={value => updatePage('quote', { eyebrow: value })} /></Field><ColorField label="Background Color" value={page.quote.backgroundColor} onChange={value => updatePage('quote', { backgroundColor: value })} /></div><div style={{ marginTop: 20 }}><Field label="Quote"><TextArea value={page.quote.quote} onChange={value => updatePage('quote', { quote: value })} rows={3} /></Field></div><div style={{ marginTop: 20 }}><Field label="Supporting Text"><TextArea value={page.quote.body} onChange={value => updatePage('quote', { body: value })} rows={3} /></Field></div><div style={{ marginTop: 20 }}><ImageUploader label="Quote Image" value={page.quote.image} onChange={value => updatePage('quote', { image: value })} category="about" source="our-story-quote" sourceLabel={form.title} sourceUrl={`/our-story/${form.slug}`} /></div></div>

    <div style={panel}><PanelTitle>03 — Four Content Cards</PanelTitle><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}><Field label="Eyebrow"><Input value={page.pillars.eyebrow} onChange={value => updatePage('pillars', { eyebrow: value })} /></Field><ColorField label="Background Color" value={page.pillars.backgroundColor} onChange={value => updatePage('pillars', { backgroundColor: value })} /></div><div style={{ marginTop: 20 }}><Field label="Title"><Input value={page.pillars.title} onChange={value => updatePage('pillars', { title: value })} /></Field></div><div style={{ marginTop: 20 }}><Field label="Introduction"><TextArea value={page.pillars.intro} onChange={value => updatePage('pillars', { intro: value })} rows={3} /></Field></div>{page.pillars.items.map((item, index) => <div key={index} style={{ marginTop: 24, paddingTop: 22, borderTop: '1px solid #eee' }}><div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, letterSpacing: '.1em', textTransform: 'uppercase', marginBottom: 15 }}>Card {index + 1}</div><div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: 20 }}><Field label="Title"><Input value={item.title} onChange={value => updatePillar(index, { title: value })} /></Field><Field label="Text"><TextArea value={item.text} onChange={value => updatePillar(index, { text: value })} rows={3} /></Field></div><div style={{ marginTop: 18 }}><ImageUploader label="Card Image" value={item.image} onChange={value => updatePillar(index, { image: value })} category="about" source="our-story-card-detail" sourceLabel={`${form.title} — ${item.title}`} sourceUrl={`/our-story/${form.slug}`} /></div></div>)}</div>

    <div style={panel}><PanelTitle>04 — Closing Section</PanelTitle><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}><Field label="Eyebrow"><Input value={page.closing.eyebrow} onChange={value => updatePage('closing', { eyebrow: value })} /></Field><ColorField label="Background Color" value={page.closing.backgroundColor} onChange={value => updatePage('closing', { backgroundColor: value })} /></div><div style={{ marginTop: 20 }}><Field label="Title"><Input value={page.closing.title} onChange={value => updatePage('closing', { title: value })} /></Field></div>{page.closing.paragraphs.map((paragraph, index) => <div key={index} style={{ marginTop: 20 }}><Field label={`Paragraph ${index + 1}`}><TextArea value={paragraph} onChange={value => updatePage('closing', { paragraphs: page.closing.paragraphs.map((item, itemIndex) => itemIndex === index ? value : item) })} rows={3} /></Field></div>)}<div style={{ marginTop: 20 }}><ImageUploader label="Closing Image" value={page.closing.image} onChange={value => updatePage('closing', { image: value })} category="about" source="our-story-closing" sourceLabel={form.title} sourceUrl={`/our-story/${form.slug}`} /></div></div>

    <div style={panel}><PanelTitle>CTA Section</PanelTitle><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}><Field label="Eyebrow"><Input value={page.cta.eyebrow} onChange={value => updatePage('cta', { eyebrow: value })} /></Field><Field label="Title"><Input value={page.cta.title} onChange={value => updatePage('cta', { title: value })} /></Field><Field label="Button Label"><Input value={page.cta.buttonLabel} onChange={value => updatePage('cta', { buttonLabel: value })} /></Field><Field label="Button Link"><Input value={page.cta.buttonHref} onChange={value => updatePage('cta', { buttonHref: value })} /></Field><ColorField label="Section Background" value={page.cta.backgroundColor} onChange={value => updatePage('cta', { backgroundColor: value })} /><ColorField label="Section Text" value={page.cta.textColor} onChange={value => updatePage('cta', { textColor: value })} /><ColorField label="Button Background" value={page.cta.buttonBackgroundColor} onChange={value => updatePage('cta', { buttonBackgroundColor: value })} /><ColorField label="Button Text" value={page.cta.buttonTextColor} onChange={value => updatePage('cta', { buttonTextColor: value })} /></div><div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: 20, marginTop: 20 }}><ImageUploader label="CTA Texture / Background Image" value={page.cta.textureImage} onChange={value => updatePage('cta', { textureImage: value })} category="about" source="our-story-cta" sourceLabel={form.title} sourceUrl={`/our-story/${form.slug}`} /><Field label="Texture Opacity (%)"><input type="number" min={0} max={100} value={page.cta.textureOpacity} onChange={event => updatePage('cta', { textureOpacity: Number(event.target.value) })} style={inputStyle} /></Field></div></div>

    <div style={panel}><PanelTitle>Recommendation Section</PanelTitle><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}><Field label="Eyebrow"><Input value={page.recommendations.eyebrow} onChange={value => updatePage('recommendations', { eyebrow: value })} /></Field><ColorField label="Background Color" value={page.recommendations.backgroundColor} onChange={value => updatePage('recommendations', { backgroundColor: value })} /><Field label="Title"><Input value={page.recommendations.title} onChange={value => updatePage('recommendations', { title: value })} /></Field><Field label="Description"><TextArea value={page.recommendations.description} onChange={value => updatePage('recommendations', { description: value })} rows={3} /></Field></div></div>

    <div style={{ display: 'flex', gap: 12, marginBottom: 32 }}><button type="submit" disabled={isPending} style={{ padding: '11px 30px', fontSize: 12, letterSpacing: '.1em', textTransform: 'uppercase', background: isPending ? '#eaa5c4' : ACCENT, color: '#fff', border: 0, cursor: isPending ? 'not-allowed' : 'pointer' }}>{isPending ? 'Saving...' : 'Save Complete Page'}</button><button type="button" onClick={onCancel} style={{ padding: '10px 24px', fontSize: 12, letterSpacing: '.1em', textTransform: 'uppercase', background: 'transparent', color: '#888', border: '1px solid #ddd', cursor: 'pointer' }}>Cancel</button></div>
  </form>;
}

export default function AdminOurStory() {
  const utils = trpc.useUtils();
  const { data: sections = [], isLoading } = trpc.ourStory.listSections.useQuery();
  const [editingId, setEditingId] = React.useState<number | 'new' | null>(null);
  const invalidate = () => Promise.all([utils.ourStory.listSections.invalidate(), utils.ourStory.listPublicSections.invalidate()]);
  const createMutation = trpc.ourStory.createSection.useMutation({ onSuccess: () => { invalidate(); setEditingId(null); toast.success('Our Story page created'); }, onError: error => toast.error(error.message) });
  const updateMutation = trpc.ourStory.updateSection.useMutation({ onSuccess: () => { invalidate(); setEditingId(null); toast.success('Our Story page saved'); }, onError: error => toast.error(error.message) });
  const deleteMutation = trpc.ourStory.deleteSection.useMutation({ onSuccess: () => { invalidate(); toast.success('Our Story page deleted'); }, onError: error => toast.error(error.message) });
  const editing = editingId === 'new' ? null : sections.find(section => section.id === editingId);
  const toForm = (section: typeof sections[number]): StoryForm => ({ slug: section.slug, eyebrow: section.eyebrow ?? '', title: section.title, content: section.content, image: section.image ?? '', isVisible: section.isVisible, sortOrder: section.sortOrder, pageContent: normalizeOurStoryPage(section.pageContent, section.title, section.content, section.image ?? '') });
  const newForm: StoryForm = { slug: '', eyebrow: '', title: '', content: '', image: '', isVisible: true, sortOrder: sections.length, pageContent: createDefaultOurStoryPage('New Story', '', '') };

  return <AdminLayout title="Our Story"><div style={{ padding: 32, maxWidth: 1050 }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 28 }}><div><h1 style={{ fontSize: 22, fontWeight: 300, letterSpacing: '.1em', textTransform: 'uppercase', color: '#1a1a1a', margin: 0 }}>Our Story Pages</h1><p style={{ fontSize: 13, color: '#888', margin: '5px 0 0' }}>Edit every image, text block, section color and CTA in the public page template.</p></div>{editingId === null && <button onClick={() => setEditingId('new')} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 20px', fontSize: 12, letterSpacing: '.1em', textTransform: 'uppercase', background: ACCENT, color: '#fff', border: 0, cursor: 'pointer' }}><Plus size={14} /> Add Page</button>}</div>
    {editingId !== null ? <StoryEditor key={editingId} initial={editing ? toForm(editing) : newForm} isPending={createMutation.isPending || updateMutation.isPending} onCancel={() => setEditingId(null)} onSave={form => { editing ? updateMutation.mutate({ id: editing.id, ...form }) : createMutation.mutate(form); }} /> : isLoading ? <div style={{ padding: 48, textAlign: 'center', color: '#888' }}>Loading...</div> : <div style={{ background: '#fff', border: '1px solid #eee' }}>{sections.length === 0 && <div style={{ padding: 48, textAlign: 'center', color: '#888' }}>No pages yet.</div>}{sections.map((section, index) => <div key={section.id} style={{ display: 'grid', gridTemplateColumns: '88px 1fr 105px 100px', gap: 18, alignItems: 'center', padding: 16, background: index % 2 === 0 ? '#f7f7f7' : '#fff', borderBottom: '1px solid #eee' }}><div style={{ width: 88, height: 66, background: '#e5e1d9', overflow: 'hidden' }}>{section.image && <img src={section.image} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />}</div><div><div style={{ fontSize: 14, color: '#1a1a1a', marginBottom: 4 }}>{section.title}</div><div style={{ fontSize: 11, color: '#999' }}>/our-story/{section.slug} · Order {section.sortOrder}</div></div><div style={{ fontSize: 11, color: section.isVisible ? ACCENT : '#aaa', textTransform: 'uppercase', letterSpacing: '.08em' }}>{section.isVisible ? 'Visible' : 'Hidden'}</div><div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}><button onClick={() => setEditingId(section.id)} title="Edit full page" style={{ color: '#777', background: 'none', border: 0, padding: 6, cursor: 'pointer' }}><Edit2 size={15} /></button><button onClick={() => { if (confirm(`Delete “${section.title}”?`)) deleteMutation.mutate({ id: section.id }); }} title="Delete" style={{ color: '#b00020', background: 'none', border: 0, padding: 6, cursor: 'pointer' }}><Trash2 size={15} /></button></div></div>)}</div>}
  </div></AdminLayout>;
}
