import React from 'react';
import { ArrowDown, ArrowUp, Copy, Eye, EyeOff, Plus, Trash2 } from 'lucide-react';
import ImageUploader from '@/components/ImageUploader';
import { createEditorialBlock, editorialBlockLabels, EDITORIAL_BLOCK_TYPES, type EditorialBlock, type EditorialBlockType } from '@shared/editorial-blocks';

const ACCENT = '#F5569B';
const input: React.CSSProperties = { width: '100%', padding: '9px 12px', fontSize: 13, background: '#f2f2f2', border: '1px solid #ddd', outline: 'none', color: '#2d2d2d', boxSizing: 'border-box' };
const label: React.CSSProperties = { display: 'block', fontSize: 11, fontWeight: 700, letterSpacing: '.1em', textTransform: 'uppercase', color: '#888', marginBottom: 7 };

function Field({ name, children }: { name: string; children: React.ReactNode }) { return <div><label style={label}>{name}</label>{children}</div>; }
function Color({ name, value, onChange }: { name: string; value: string; onChange: (value: string) => void }) { return <Field name={name}><div style={{ display: 'flex', gap: 8 }}><input type="color" value={/^#[0-9a-f]{6}$/i.test(value) ? value : '#000000'} onChange={event => onChange(event.target.value)} style={{ width: 42, height: 36, border: '1px solid #ddd' }} /><input value={value} onChange={event => onChange(event.target.value)} style={input} /></div></Field>; }

export default function EditorialBlocksEditor({ value, onChange, category, sourceLabel, sourceUrl }: { value: EditorialBlock[]; onChange: (blocks: EditorialBlock[]) => void; category: 'story' | 'explore' | 'about'; sourceLabel: string; sourceUrl: string }) {
  const [newType, setNewType] = React.useState<EditorialBlockType>('split');
  const update = (index: number, patch: Partial<EditorialBlock>) => onChange(value.map((block, itemIndex) => itemIndex === index ? { ...block, ...patch } : block));
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= value.length) return; const next = [...value]; [next[index], next[target]] = [next[target], next[index]]; onChange(next); };
  const add = () => onChange([...value, createEditorialBlock(newType, value.length)]);
  return <div style={{ background: '#fff', border: `1px solid #eee`, borderTop: `3px solid ${ACCENT}`, padding: 28, marginBottom: 24 }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', gap: 20, alignItems: 'flex-start', paddingBottom: 18, borderBottom: '1px solid #eee', marginBottom: 22 }}><div><div style={{ fontSize: 13, fontWeight: 600, letterSpacing: '.12em', textTransform: 'uppercase' }}>Shared Editorial Content Blocks</div><p style={{ fontSize: 12, color: '#777', lineHeight: 1.6, margin: '8px 0 0' }}>The same block library is available in Stories, Explore and Our Story. Add, repeat and reorder any layout. For future long-form pages, use at least 8 content blocks.</p></div><div style={{ minWidth: 235, display: 'flex', gap: 8 }}><select value={newType} onChange={event => setNewType(event.target.value as EditorialBlockType)} style={input}>{EDITORIAL_BLOCK_TYPES.map(type => <option value={type} key={type}>{editorialBlockLabels[type]}</option>)}</select><button type="button" onClick={add} title="Add block" style={{ width: 42, border: 0, background: ACCENT, color: '#fff', cursor: 'pointer' }}><Plus size={16} /></button></div></div>
    <div style={{ padding: '11px 14px', marginBottom: 18, background: value.length >= 8 ? '#edf7ef' : '#fff5e9', color: value.length >= 8 ? '#31733d' : '#976022', fontSize: 12 }}>{value.length} editorial block{value.length === 1 ? '' : 's'} configured. {value.length < 8 ? `${8 - value.length} more recommended for a complete new article.` : 'Long-form structure requirement met.'}</div>
    {value.length === 0 && <div style={{ padding: 30, textAlign: 'center', color: '#999', border: '1px dashed #ddd' }}>No shared blocks yet. Existing template sections remain visible until you add blocks.</div>}
    {value.map((block, index) => <div key={block.id} style={{ border: '1px solid #ddd', marginBottom: 18, background: block.visible ? '#fff' : '#f5f5f5' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '12px 14px', background: '#f7f7f7', borderBottom: '1px solid #e6e6e6' }}><strong style={{ fontSize: 12, letterSpacing: '.08em', textTransform: 'uppercase', flex: 1 }}>{String(index + 1).padStart(2, '0')} · {editorialBlockLabels[block.type]}</strong><button type="button" onClick={() => move(index, -1)} disabled={index === 0} title="Move up" style={iconButton}><ArrowUp size={15} /></button><button type="button" onClick={() => move(index, 1)} disabled={index === value.length - 1} title="Move down" style={iconButton}><ArrowDown size={15} /></button><button type="button" onClick={() => onChange([...value.slice(0, index + 1), { ...block, id: `editorial-${Date.now()}-copy` }, ...value.slice(index + 1)])} title="Duplicate" style={iconButton}><Copy size={15} /></button><button type="button" onClick={() => update(index, { visible: !block.visible })} title={block.visible ? 'Hide block' : 'Show block'} style={iconButton}>{block.visible ? <Eye size={15} /> : <EyeOff size={15} />}</button><button type="button" onClick={() => onChange(value.filter((_, itemIndex) => itemIndex !== index))} title="Delete block" style={{ ...iconButton, color: '#c9213b' }}><Trash2 size={15} /></button></div>
      <div style={{ padding: 20 }}><div style={grid}><Field name="Layout"><select value={block.type} onChange={event => update(index, createEditorialBlock(event.target.value as EditorialBlockType, index))} style={input}>{EDITORIAL_BLOCK_TYPES.map(type => <option value={type} key={type}>{editorialBlockLabels[type]}</option>)}</select></Field><Field name="Eyebrow"><input value={block.eyebrow} onChange={event => update(index, { eyebrow: event.target.value })} style={input} /></Field><Field name="Title"><input value={block.title} onChange={event => update(index, { title: event.target.value })} style={input} /></Field>{block.type === 'quote-image' && <Field name="Quote"><textarea value={block.quote} onChange={event => update(index, { quote: event.target.value })} rows={3} style={{ ...input, resize: 'vertical' }} /></Field>}<Color name="Background" value={block.backgroundColor} onChange={backgroundColor => update(index, { backgroundColor })} /><Color name="Text" value={block.textColor} onChange={textColor => update(index, { textColor })} /><Color name="Accent" value={block.accentColor} onChange={accentColor => update(index, { accentColor })} />{block.images.length > 0 && <Field name="Image Position"><select value={block.imageSide} onChange={event => update(index, { imageSide: event.target.value as 'left' | 'right' })} style={input}><option value="left">Left</option><option value="right">Right</option></select></Field>}{block.images.length > 0 && <Field name="Image Fit"><select value={block.imageFit} onChange={event => update(index, { imageFit: event.target.value as 'cover' | 'contain' })} style={input}><option value="cover">Editorial crop</option><option value="contain">Show complete image</option></select></Field>}</div>
        {block.type !== 'full-image' && block.type !== 'divider' && <div style={{ marginTop: 18 }}><Field name="Paragraphs — separate with a blank line"><textarea value={block.body.join('\n\n')} onChange={event => update(index, { body: event.target.value.split(/\n\s*\n/) })} rows={6} style={{ ...input, resize: 'vertical' }} /></Field></div>}
        {block.images.map((image, imageIndex) => <div key={imageIndex} style={{ marginTop: 18, paddingTop: 18, borderTop: '1px solid #eee' }}><ImageUploader label={`Image ${imageIndex + 1}`} value={image} onChange={url => update(index, { images: block.images.map((item, itemIndex) => itemIndex === imageIndex ? url : item) })} category={category} source={`editorial-${block.type}-${imageIndex + 1}`} sourceLabel={sourceLabel} sourceUrl={sourceUrl} /></div>)}
        {block.images.length > 0 && block.images.length < 6 && <button type="button" onClick={() => update(index, { images: [...block.images, ''], captions: [...block.captions, ''] })} style={{ marginTop: 14, padding: 0, border: 0, background: 'none', color: ACCENT, fontSize: 12, cursor: 'pointer' }}>+ Add another image</button>}
      </div>
    </div>)}
  </div>;
}

const grid: React.CSSProperties = { display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 18 };
const iconButton: React.CSSProperties = { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 29, height: 29, padding: 0, border: 0, background: 'transparent', cursor: 'pointer' };
