import { Link } from 'wouter';
import { useMemo } from 'react';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import { useMediaObjectPosition } from '@/lib/media-position';
import { trpc } from '@/lib/trpc';
import type { ExplorePageContent } from '@shared/explore';

const DISPLAY = "var(--font-travel-condensed, 'League Gothic', 'Arial Narrow', Impact, sans-serif)";
const SANS = "var(--font-travel-sans, 'Cabin', 'Helvetica Neue', Arial, sans-serif)";

export default function ExploreTemplate({ content }: { content: ExplorePageContent }) {
  const getPosition = useMediaObjectPosition();
  const { data: availableStories = [] } = trpc.cms.listStories.useQuery();
  const { data: homepageAssets } = trpc.media.getHomepageAssets.useQuery();
  const ctaTexture = homepageAssets?.cta?.url || '';
  const ctaTextureOpacity = Math.max(0, Math.min(1, Number(homepageAssets?.cta?.opacity ?? 28) / 100));
  const selectStories = (selectedIds: number[]) => {
    const selected = selectedIds.length ? selectedIds.map(id => availableStories.find(story => story.id === id)).filter(Boolean) : [...availableStories].sort(() => Math.random() - .5).slice(0, 3);
    return selected.slice(0, 3).map((story: any) => ({ category: story.pageContent?.meta?.category || 'Journal', title: story.title, description: story.pageContent?.meta?.excerpt || String(story.content || '').replace(/\s+/g, ' ').slice(0, 180), href: `/stories/article/${story.slug}`, image: story.coverImage || '' }));
  };
  const perspectiveStories = useMemo(() => selectStories(content.perspectives.selectedStoryIds), [availableStories, content.perspectives.selectedStoryIds]);
  const relatedStories = useMemo(() => selectStories(content.stories.selectedStoryIds), [availableStories, content.stories.selectedStoryIds]);
  const perspectiveItems = perspectiveStories.length ? perspectiveStories : content.perspectives.items;
  const storyItems = relatedStories.length ? relatedStories : content.stories.items;
  const picture = (url: string, alt: string, height: string | number) => <img src={url} alt={alt} className="image" style={{ height, objectPosition: getPosition(url) }} />;
  return <div className="explore-editorial" style={{ background: content.introduction.backgroundColor, color: content.introduction.textColor }}>
    <style>{`
      .explore-editorial{font-family:${SANS}}.explore-editorial .wrap{width:min(1320px,calc(100% - 64px));margin:0 auto}.explore-editorial .display{font-family:${DISPLAY};font-weight:400;letter-spacing:.045em;line-height:.92;text-transform:uppercase}.explore-editorial .eyebrow{font-size:11px;font-weight:700;letter-spacing:.19em;text-transform:uppercase}.explore-editorial .copy{font-size:17px;line-height:1.72;letter-spacing:.035em;color:inherit;opacity:.76}.explore-editorial .image{display:block;width:100%;object-fit:cover}.explore-editorial .visual-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:32px;align-items:start}.explore-editorial .visual-a{grid-column:1/9}.explore-editorial .visual-b{grid-column:9/13;margin-top:170px}.explore-editorial .visual-c{grid-column:2/6;margin-top:72px}.explore-editorial .visual-copy{grid-column:7/12;margin-top:150px}.explore-editorial .details-grid{display:grid;grid-template-columns:1.35fr .85fr 1fr;gap:22px;align-items:end}.explore-editorial .perspective-grid,.explore-editorial .story-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:28px}.explore-editorial .perspective:nth-child(2){margin-top:90px}.explore-editorial .button{display:inline-block;border:2px solid currentColor;border-radius:3px;padding:13px 30px;font-size:12px;font-weight:700;letter-spacing:.14em;text-transform:uppercase;text-decoration:none}@media(max-width:767px){.explore-editorial .wrap{width:calc(100% - 40px)}.explore-editorial .visual-grid,.explore-editorial .details-grid,.explore-editorial .perspective-grid,.explore-editorial .story-grid{display:block}.explore-editorial .visual-a,.explore-editorial .visual-b,.explore-editorial .visual-c,.explore-editorial .visual-copy,.explore-editorial .perspective{margin:0 0 28px}.explore-editorial .detail,.explore-editorial .related-story{margin-bottom:36px}}
    `}</style>
    <Navigation />
    <header className="relative flex items-end overflow-hidden" style={{ minHeight: 'min(850px,90vh)', background: content.hero.backgroundColor }}><img src={content.hero.image} alt={content.hero.title} className="absolute inset-0 image h-full" style={{ objectPosition: getPosition(content.hero.image) }} /><div className="absolute inset-0" style={{ background: `rgba(9,18,14,${content.hero.overlayOpacity / 100})` }} /><div className="relative z-10 text-white" style={{ padding: '0 clamp(24px,7vw,110px) clamp(62px,8vw,108px)' }}><p className="eyebrow">{content.hero.eyebrow}</p><h1 className="display" style={{ fontSize: 'clamp(68px,11vw,156px)', margin: 0 }}>{content.hero.title}</h1><p style={{ maxWidth: 720, margin: '24px 0 0', fontSize: 'clamp(17px,1.6vw,23px)', lineHeight: 1.5 }}>{content.hero.subtitle}</p></div></header>
    <section style={{ padding: 'clamp(90px,11vw,160px) 0', background: content.introduction.backgroundColor, color: content.introduction.textColor }}><div className="wrap grid md:grid-cols-[.7fr_1.8fr] gap-12 md:gap-24 items-start"><p className="eyebrow" style={{ color: '#8b5a3c', margin: 0 }}>{content.introduction.eyebrow}</p><p style={{ margin: 0, fontSize: 'clamp(23px,2.7vw,38px)', lineHeight: 1.32, maxWidth: 920 }}>{content.introduction.text}</p></div></section>
    <section style={{ paddingBottom: 'clamp(110px,13vw,190px)', background: content.visual.backgroundColor }}><div className="wrap visual-grid"><figure className="visual-a" style={{ margin: 0 }}>{picture(content.visual.images[0], content.visual.title, 'clamp(430px,55vw,720px)')}</figure><figure className="visual-b" style={{ marginBottom: 0 }}>{picture(content.visual.images[1], content.visual.title, 'clamp(420px,48vw,640px)')}</figure><figure className="visual-c" style={{ marginBottom: 0 }}>{picture(content.visual.images[2], content.visual.title, 'clamp(450px,52vw,690px)')}</figure><div className="visual-copy"><p className="eyebrow" style={{ color: '#8b5a3c' }}>{content.visual.eyebrow}</p><h2 className="display" style={{ fontSize: 'clamp(44px,5vw,72px)', color: '#17352d' }}>{content.visual.title}</h2>{content.visual.paragraphs.map((p, i) => <p className="copy" key={i}>{p}</p>)}</div></div></section>
    <section style={{ background: content.details.backgroundColor, padding: 'clamp(86px,10vw,140px) 0' }}><div className="wrap"><div className="flex justify-between items-end gap-8" style={{ marginBottom: 48 }}><div><p className="eyebrow" style={{ color: '#8b5a3c' }}>{content.details.eyebrow}</p><h2 className="display" style={{ fontSize: 'clamp(46px,6vw,78px)', margin: 0 }}>{content.details.title}</h2></div><p className="copy hidden md:block" style={{ maxWidth: 380 }}>{content.details.description}</p></div><div className="details-grid">{content.details.items.slice(0,3).map((item,i)=><figure className="detail" key={i} style={{margin:0}}>{picture(item.image,item.title,i===0?520:i===1?390:455)}<figcaption className="eyebrow" style={{marginTop:15}}>{item.title}</figcaption></figure>)}</div><div className="grid grid-cols-2 md:grid-cols-3 gap-5 md:gap-7" style={{marginTop:22}}>{content.details.items.slice(3,6).map((item,i)=><figure key={i} style={{margin:0}}>{picture(item.image,item.title,'clamp(220px,27vw,360px)')}<figcaption className="eyebrow" style={{marginTop:15}}>{item.title}</figcaption></figure>)}</div></div></section>
    <section style={{ padding: 'clamp(120px,16vw,230px) 0', background: content.statement.backgroundColor, color: content.statement.textColor }}><div className="wrap"><p className="eyebrow" style={{opacity:.72}}>{content.statement.eyebrow}</p><p style={{fontSize:'clamp(34px,4.6vw,66px)',lineHeight:1.14,maxWidth:1040,margin:0}}>{content.statement.text}</p></div></section>
    <section style={{padding:'clamp(100px,12vw,170px) 0',background:content.perspectives.backgroundColor}}><div className="wrap"><p className="eyebrow" style={{color:'#8b5a3c',marginBottom:14}}>{content.perspectives.eyebrow}</p><h2 className="display" style={{fontSize:'clamp(46px,6vw,78px)',margin:'0 0 48px'}}>{content.perspectives.title}</h2><div className="perspective-grid">{perspectiveItems.map((item,i)=><Link href={item.href} className="perspective block text-inherit no-underline" key={i}>{picture(item.image,item.title,i===0?570:430)}<h3 className="display" style={{fontSize:'clamp(32px,3.5vw,48px)',margin:'24px 0 12px'}}>{item.title}</h3><p className="copy" style={{margin:0,fontSize:15}}>{item.description}</p></Link>)}</div></div></section>
    <section style={{padding:'clamp(90px,10vw,140px) 0',background:content.stories.backgroundColor}}><div className="wrap"><div className="flex justify-between items-end" style={{marginBottom:44}}><div><p className="eyebrow" style={{color:'#8b5a3c'}}>{content.stories.eyebrow}</p><h2 className="display" style={{fontSize:'clamp(46px,6vw,78px)',margin:0}}>{content.stories.title}</h2></div></div><div className="story-grid">{storyItems.map((item,i)=><Link href={item.href} className="related-story block text-inherit no-underline" key={i}>{picture(item.image,item.title,390)}<p className="eyebrow" style={{color:'#8b5a3c',margin:'20px 0 10px'}}>{item.category}</p><h3 style={{fontSize:23,lineHeight:1.3,fontWeight:500,margin:0}}>{item.title}</h3></Link>)}</div></div></section>
    <section className="relative overflow-hidden text-center" style={{padding:'clamp(90px,10vw,140px) 24px',background:content.cta.backgroundColor,color:content.cta.textColor}}>{ctaTexture&&<div aria-hidden="true" className="absolute inset-0" style={{backgroundImage:`url(${ctaTexture})`,backgroundSize:'420px 420px',backgroundRepeat:'repeat',opacity:ctaTextureOpacity}}/>}<div className="relative"><p className="eyebrow" style={{opacity:.72}}>{content.cta.eyebrow}</p><h2 className="display" style={{fontSize:'clamp(52px,7vw,94px)',margin:'0 auto 36px',maxWidth:920}}>{content.cta.title}</h2><Link href={content.cta.buttonHref} className="button" style={{background:content.cta.buttonBackgroundColor,color:content.cta.buttonTextColor,borderColor:content.cta.buttonBackgroundColor}}>{content.cta.buttonLabel}</Link></div></section>
    <Footer />
  </div>;
}
