import { Link } from 'wouter';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import { useMediaObjectPosition } from '@/lib/media-position';
import type { ExplorePageContent } from '@shared/explore';

const DISPLAY = "var(--font-travel-condensed, 'League Gothic', 'Arial Narrow', Impact, sans-serif)";
const SANS = "var(--font-travel-sans, 'Cabin', 'Helvetica Neue', Arial, sans-serif)";

export default function ExploreActivityDetail({ content }: { content: ExplorePageContent }) {
  const detail = content.activityDetail;
  const position = useMediaObjectPosition();
  if (!detail) return null;
  const image = (src: string, alt: string, className = '') => <img src={src} alt={alt} className={`activity-image ${className}`} style={{objectPosition:position(src)}}/>;
  return <div className="activity-page" style={{fontFamily:SANS,background:'#f3efe6',color:'#17251f'}}>
    <style>{`
      .activity-page .wrap{width:min(1260px,calc(100% - 64px));margin:0 auto}.activity-page .display{font-family:${DISPLAY};font-weight:400;letter-spacing:.045em;line-height:.94;text-transform:uppercase}.activity-page .eyebrow{font-size:11px;font-weight:700;letter-spacing:.19em;text-transform:uppercase}.activity-page .copy{font-size:17px;line-height:1.75;letter-spacing:.02em;color:#4f5953}.activity-page .activity-image{display:block;width:100%;height:100%;object-fit:cover}.activity-page .button{display:inline-block;padding:14px 30px;background:#111;color:#fff;text-decoration:none;font-size:12px;font-weight:700;letter-spacing:.14em;text-transform:uppercase;border:2px solid #111}.activity-page .info-grid{display:grid;grid-template-columns:repeat(5,1fr);border-top:1px solid #c8c2b7;border-bottom:1px solid #c8c2b7}.activity-page .info-cell{padding:25px 22px;border-right:1px solid #c8c2b7}.activity-page .info-cell:last-child{border:0}.activity-page .two-col{display:grid;grid-template-columns:1fr 1fr;gap:clamp(42px,8vw,120px);align-items:center}.activity-page .photo-pair{display:grid;grid-template-columns:1.15fr .85fr;gap:24px;align-items:end}.activity-page .photo-pair img:first-child{height:620px}.activity-page .photo-pair img:last-child{height:450px}.activity-page .option-grid,.activity-page .practical-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1px;background:#c8c2b7;border:1px solid #c8c2b7}.activity-page .option-card,.activity-page .practical-card{background:#f3efe6;padding:34px}.activity-page .principle-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:22px}.activity-page .principle{border-top:1px solid rgba(245,241,232,.4);padding-top:18px;font-size:15px;line-height:1.55}@media(max-width:767px){.activity-page .wrap{width:calc(100% - 40px)}.activity-page .two-col,.activity-page .photo-pair,.activity-page .option-grid,.activity-page .practical-grid,.activity-page .principle-grid{display:block}.activity-page .photo-pair img{height:380px!important;margin-bottom:20px}.activity-page .info-grid{grid-template-columns:1fr 1fr}.activity-page .info-cell:nth-child(even){border-right:0}.activity-page .info-cell:last-child{grid-column:1/-1}.activity-page .option-card,.activity-page .practical-card{margin-bottom:1px}.activity-page .principle{margin-bottom:28px}}
    `}</style>
    <Navigation/>
    <header className="relative flex items-end overflow-hidden" style={{minHeight:'min(850px,92vh)',background:'#17352d'}}>{image(content.hero.image,content.hero.title,'absolute inset-0')}<div className="absolute inset-0" style={{background:`rgba(9,18,14,${content.hero.overlayOpacity/100})`}}/><div className="relative z-10 text-white" style={{padding:'0 clamp(24px,7vw,110px) clamp(65px,8vw,110px)',maxWidth:1120}}><p className="eyebrow">Explore / {detail.category}</p><h1 className="display" style={{fontSize:'clamp(66px,10vw,145px)',margin:0}}>{content.hero.title}</h1><p style={{maxWidth:720,fontSize:'clamp(17px,1.6vw,23px)',lineHeight:1.55,margin:'25px 0 30px'}}>{detail.excerpt}</p><Link href={content.activity.registrationHref} className="button">{content.activity.registrationLabel}</Link></div></header>
    <section style={{padding:'40px 0',background:'#e5ded2'}}><div className="wrap"><p className="copy" style={{maxWidth:820,margin:'0 0 28px'}}>{content.activity.note}</p><div className="info-grid"><Info label="Availability" value={content.activity.statusLabel}/><Info label="Arrangement" value={content.activity.dateLabel}/><Info label="Duration" value={content.activity.duration}/><Info label="Group" value={content.activity.groupSize}/><Info label="Participation" value={content.activity.difficulty}/></div><p className="eyebrow" style={{margin:'18px 0 0',opacity:.6}}>{content.activity.location}</p></div></section>
    <section style={{padding:'clamp(90px,12vw,170px) 0'}}><div className="wrap two-col"><div><Label text={detail.purpose.eyebrow}/><Title text={detail.purpose.title}/>{detail.purpose.paragraphs.map((p,i)=><p className="copy" key={i}>{p}</p>)}</div><div style={{height:'clamp(430px,58vw,690px)'}}>{image(detail.purpose.image,detail.purpose.title)}</div></div></section>
    <section style={{padding:'clamp(90px,11vw,155px) 0',background:'#ddd5c7'}}><div className="wrap"><div style={{maxWidth:780,marginBottom:55}}><Label text={detail.currentWork.eyebrow}/><Title text={detail.currentWork.title}/>{detail.currentWork.paragraphs.map((p,i)=><p className="copy" key={i}>{p}</p>)}</div><div className="photo-pair">{detail.currentWork.images.map((src,i)=>image(src,`${detail.currentWork.title} ${i+1}`))}</div></div></section>
    <section style={{padding:'clamp(90px,11vw,155px) 0',background:'#f3efe6'}}><div className="wrap"><div className="two-col" style={{alignItems:'end',marginBottom:50}}><div><Label text={detail.participation.eyebrow}/><Title text={detail.participation.title}/></div><p className="copy">{detail.participation.introduction}</p></div><div className="option-grid">{detail.participation.items.map((item,i)=><div className="option-card" key={item.title}><p className="eyebrow" style={{color:'#9b5e3d'}}>0{i+1}</p><h3 style={{fontSize:25,fontWeight:500,margin:'16px 0 12px'}}>{item.title}</h3><p className="copy" style={{fontSize:15,margin:0}}>{item.description}</p></div>)}</div></div></section>
    <section style={{padding:'clamp(90px,12vw,170px) 0',background:'#cfd2c3'}}><div className="wrap two-col"><div style={{height:'clamp(440px,55vw,650px)'}}>{image(detail.flexibility.image,detail.flexibility.title)}</div><div><Label text={detail.flexibility.eyebrow}/><Title text={detail.flexibility.title}/>{detail.flexibility.paragraphs.map((p,i)=><p className="copy" key={i}>{p}</p>)}<div className="grid grid-cols-2 gap-x-6 gap-y-3" style={{marginTop:30}}>{detail.flexibility.points.map(point=><p className="eyebrow" key={point} style={{borderTop:'1px solid #9fa79d',paddingTop:12,margin:0}}>{point}</p>)}</div></div></div></section>
    <section style={{padding:'clamp(90px,11vw,155px) 0',background:'#fff'}}><div className="wrap"><div style={{maxWidth:780,marginBottom:52}}><Label text={detail.people.eyebrow}/><Title text={detail.people.title}/>{detail.people.paragraphs.map((p,i)=><p className="copy" key={i}>{p}</p>)}</div><div className="photo-pair">{detail.people.images.map((src,i)=>image(src,`${detail.people.title} ${i+1}`))}</div></div></section>
    <section style={{padding:'clamp(90px,11vw,150px) 0',background:'#e8e1d5'}}><div className="wrap"><div style={{maxWidth:800,marginBottom:48}}><Label text={detail.practical.eyebrow}/><Title text={detail.practical.title}/><p className="copy">{detail.practical.introduction}</p></div><div className="practical-grid">{detail.practical.items.map(item=><div className="practical-card" key={item.title}><h3 style={{fontSize:22,fontWeight:500,margin:'0 0 10px'}}>{item.title}</h3><p className="copy" style={{fontSize:15,margin:0}}>{item.description}</p></div>)}</div></div></section>
    <section style={{padding:'clamp(100px,13vw,185px) 0',background:'#17352d',color:'#f5f1e8'}}><div className="wrap"><Label text={detail.principles.eyebrow} light/><h2 className="display" style={{fontSize:'clamp(58px,8vw,112px)',maxWidth:900,margin:'0 0 65px'}}>{detail.principles.title}</h2><div className="principle-grid">{detail.principles.items.map((item,i)=><div className="principle" key={item}>0{i+1}<br/><br/>{item}</div>)}</div></div></section>
    <section style={{padding:'clamp(90px,12vw,170px) 0',background:'#f3efe6'}}><div className="wrap two-col"><div><Label text={detail.closing.eyebrow}/><Title text={detail.closing.title}/>{detail.closing.paragraphs.map((p,i)=><p className="copy" key={i}>{p}</p>)}<Link href={content.activity.registrationHref} className="button" style={{marginTop:24}}>{content.activity.registrationLabel}</Link></div><div style={{height:'clamp(430px,55vw,650px)'}}>{image(detail.closing.image,detail.closing.title)}</div></div></section>
    <Footer/>
  </div>;
}

function Info({label,value}:{label:string;value:string}) { return <div className="info-cell"><p className="eyebrow" style={{opacity:.55,margin:'0 0 8px'}}>{label}</p><strong style={{fontSize:14,lineHeight:1.4}}>{value}</strong></div>; }
function Label({text,light=false}:{text:string;light?:boolean}) { return <p className="eyebrow" style={{color:light?'#c79a72':'#9b5e3d',margin:'0 0 18px'}}>{text}</p>; }
function Title({text}:{text:string}) { return <h2 className="display" style={{fontSize:'clamp(48px,6vw,82px)',margin:'0 0 28px'}}>{text}</h2>; }
